package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 4:51:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HisServiceMedicaltest generated by hbm2java
 */
public class PatientHistory  implements java.io.Serializable {
     private int patientHistoryID;
     private String value;
     private String name;
     private Character patientTypeID;
     private Date birthday;
     private Character genderID;
     private String address;
     private String assuranceID;
     private int patientID;

    public PatientHistory() {
    }

    public int getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(int patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Character getPatientTypeID() {
        return patientTypeID;
    }

    public void setPatientTypeID(Character patientTypeID) {
        this.patientTypeID = patientTypeID;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Character getGenderID() {
        return genderID;
    }

    public void setGenderID(Character genderID) {
        this.genderID = genderID;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAssuranceID() {
        return assuranceID;
    }

    public void setAssuranceID(String assuranceID) {
        this.assuranceID = assuranceID;
    }

    public int getPatientID() {
        return patientID;
    }

    public void setPatientID(int patientID) {
        this.patientID = patientID;
    }
}


