package com.vanminh.model;
// Generated Jun 3, 2016 3:57:44 PM by Hibernate Tools 4.3.1



/**
 * HISPatientHistory generated by hbm2java
 */
public class HISPatientHistory  implements java.io.Serializable {


     private int patientHistory_ID;

    public HISPatientHistory() {
    }

    public HISPatientHistory(int patientHistory_ID) {
       this.patientHistory_ID = patientHistory_ID;
    }
   
    public int getPatientHistory_ID() {
        return this.patientHistory_ID;
    }
    
    public void setPatientHistory_ID(int patientHistory_ID) {
        this.patientHistory_ID = patientHistory_ID;
    }




}


