package com.isofh.hibernate.entities;
// Generated May 24, 2016 4:58:58 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HisServiceMedictestgroup generated by hbm2java
 */
public class HisServiceMedictestgroup  implements java.io.Serializable {


     private long hisServiceMedictestgroupId;
     private Long adClientId;
     private Long adOrgId;
     private Date created;
     private Long createdby;
     private Character isactive;
     private Date updated;
     private Long updatedby;
     private Long hisPatienthistoryId;
     private String tag2;
     private String status;
     private String hisTimesurgery;
     private Long hisDepartmentId;
     private char iscreatedform;

    public HisServiceMedictestgroup() {
    }

	
    public HisServiceMedictestgroup(long hisServiceMedictestgroupId, char iscreatedform) {
        this.hisServiceMedictestgroupId = hisServiceMedictestgroupId;
        this.iscreatedform = iscreatedform;
    }
    public HisServiceMedictestgroup(long hisServiceMedictestgroupId, Long adClientId, Long adOrgId, Date created, Long createdby, Character isactive, Date updated, Long updatedby, Long hisPatienthistoryId, String tag2, String status, String hisTimesurgery, Long hisDepartmentId, char iscreatedform) {
       this.hisServiceMedictestgroupId = hisServiceMedictestgroupId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.created = created;
       this.createdby = createdby;
       this.isactive = isactive;
       this.updated = updated;
       this.updatedby = updatedby;
       this.hisPatienthistoryId = hisPatienthistoryId;
       this.tag2 = tag2;
       this.status = status;
       this.hisTimesurgery = hisTimesurgery;
       this.hisDepartmentId = hisDepartmentId;
       this.iscreatedform = iscreatedform;
    }
   
    public long getHisServiceMedictestgroupId() {
        return this.hisServiceMedictestgroupId;
    }
    
    public void setHisServiceMedictestgroupId(long hisServiceMedictestgroupId) {
        this.hisServiceMedictestgroupId = hisServiceMedictestgroupId;
    }
    public Long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(Long adClientId) {
        this.adClientId = adClientId;
    }
    public Long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(Long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(Long updatedby) {
        this.updatedby = updatedby;
    }
    public Long getHisPatienthistoryId() {
        return this.hisPatienthistoryId;
    }
    
    public void setHisPatienthistoryId(Long hisPatienthistoryId) {
        this.hisPatienthistoryId = hisPatienthistoryId;
    }
    public String getTag2() {
        return this.tag2;
    }
    
    public void setTag2(String tag2) {
        this.tag2 = tag2;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getHisTimesurgery() {
        return this.hisTimesurgery;
    }
    
    public void setHisTimesurgery(String hisTimesurgery) {
        this.hisTimesurgery = hisTimesurgery;
    }
    public Long getHisDepartmentId() {
        return this.hisDepartmentId;
    }
    
    public void setHisDepartmentId(Long hisDepartmentId) {
        this.hisDepartmentId = hisDepartmentId;
    }
    public char getIscreatedform() {
        return this.iscreatedform;
    }
    
    public void setIscreatedform(char iscreatedform) {
        this.iscreatedform = iscreatedform;
    }




}


