
package com.isofh.signer.viettel.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SignServerWSService", targetNamespace = "http://ws.viettel.com/", wsdlLocation = "file:/mnt/workspace/workspace/java/signer/src/main/resources/SignServerWSService.wsdl")
public class SignServerWSService
    extends Service
{

    private final static URL SIGNSERVERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIGNSERVERWSSERVICE_EXCEPTION;
    private final static QName SIGNSERVERWSSERVICE_QNAME = new QName("http://ws.viettel.com/", "SignServerWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/mnt/workspace/workspace/java/signer/src/main/resources/SignServerWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIGNSERVERWSSERVICE_WSDL_LOCATION = url;
        SIGNSERVERWSSERVICE_EXCEPTION = e;
    }

    public SignServerWSService() {
        super(__getWsdlLocation(), SIGNSERVERWSSERVICE_QNAME);
    }

    public SignServerWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIGNSERVERWSSERVICE_QNAME, features);
    }

    public SignServerWSService(URL wsdlLocation) {
        super(wsdlLocation, SIGNSERVERWSSERVICE_QNAME);
    }

    public SignServerWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIGNSERVERWSSERVICE_QNAME, features);
    }

    public SignServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SignServerWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SignServerWS
     */
    @WebEndpoint(name = "SignServerWSPort")
    public SignServerWS getSignServerWSPort() {
        return super.getPort(new QName("http://ws.viettel.com/", "SignServerWSPort"), SignServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SignServerWS
     */
    @WebEndpoint(name = "SignServerWSPort")
    public SignServerWS getSignServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.viettel.com/", "SignServerWSPort"), SignServerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIGNSERVERWSSERVICE_EXCEPTION!= null) {
            throw SIGNSERVERWSSERVICE_EXCEPTION;
        }
        return SIGNSERVERWSSERVICE_WSDL_LOCATION;
    }

}
