
package com.isofh.signer.viettel.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SignServerWS", targetNamespace = "http://ws.viettel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignServerWS {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignDataBase64ResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signHashBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignHashBase64")
    @ResponseWrapper(localName = "signHashBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignHashBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/signHashBase64Request", output = "http://ws.viettel.com/SignServerWS/signHashBase64Response")
    public SignDataBase64ResponceBO signHashBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.CertListResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reloadCertList", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.ReloadCertList")
    @ResponseWrapper(localName = "reloadCertListResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.ReloadCertListResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/reloadCertListRequest", output = "http://ws.viettel.com/SignServerWS/reloadCertListResponse")
    public CertListResponceBO reloadCertList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.CertInfoResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertInfo", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.GetCertInfo")
    @ResponseWrapper(localName = "getCertInfoResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.GetCertInfoResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/getCertInfoRequest", output = "http://ws.viettel.com/SignServerWS/getCertInfoResponse")
    public CertInfoResponceBO getCertInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignDataBase64ResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signDataBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignDataBase64")
    @ResponseWrapper(localName = "signDataBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignDataBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/signDataBase64Request", output = "http://ws.viettel.com/SignServerWS/signDataBase64Response")
    public SignDataBase64ResponceBO signDataBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signXmlBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignXmlBase64")
    @ResponseWrapper(localName = "signXmlBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignXmlBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/signXmlBase64Request", output = "http://ws.viettel.com/SignServerWS/signXmlBase64Response")
    public SignFileResponceBO signXmlBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signXmlFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignXmlFilePath")
    @ResponseWrapper(localName = "signXmlFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignXmlFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signXmlFilePathRequest", output = "http://ws.viettel.com/SignServerWS/signXmlFilePathResponse")
    public SignFileResponceBO signXmlFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signOOXmlBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignOOXmlBase64")
    @ResponseWrapper(localName = "signOOXmlBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignOOXmlBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/signOOXmlBase64Request", output = "http://ws.viettel.com/SignServerWS/signOOXmlBase64Response")
    public SignFileResponceBO signOOXmlBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64")
    @ResponseWrapper(localName = "signPdfBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfBase64Request", output = "http://ws.viettel.com/SignServerWS/signPdfBase64Response")
    public SignFileResponceBO signPdfBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePath")
    @ResponseWrapper(localName = "signPdfFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfFilePathRequest", output = "http://ws.viettel.com/SignServerWS/signPdfFilePathResponse")
    public SignFileResponceBO signPdfFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifySignatureBase64ResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifySignatureBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifySignatureBase64")
    @ResponseWrapper(localName = "verifySignatureBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifySignatureBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifySignatureBase64Request", output = "http://ws.viettel.com/SignServerWS/verifySignatureBase64Response")
    public VerifySignatureBase64ResponceBO verifySignatureBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signOOXmlFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignOOXmlFilePath")
    @ResponseWrapper(localName = "signOOXmlFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignOOXmlFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signOOXmlFilePathRequest", output = "http://ws.viettel.com/SignServerWS/signOOXmlFilePathResponse")
    public SignFileResponceBO signOOXmlFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfBase64RectangleText", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64RectangleText")
    @ResponseWrapper(localName = "signPdfBase64RectangleTextResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64RectangleTextResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfBase64RectangleTextRequest", output = "http://ws.viettel.com/SignServerWS/signPdfBase64RectangleTextResponse")
    public SignFileResponceBO signPdfBase64RectangleText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayRectangleTextConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfFilePathRectangleText", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathRectangleText")
    @ResponseWrapper(localName = "signPdfFilePathRectangleTextResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathRectangleTextResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfFilePathRectangleTextRequest", output = "http://ws.viettel.com/SignServerWS/signPdfFilePathRectangleTextResponse")
    public SignFileResponceBO signPdfFilePathRectangleText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayRectangleTextConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfBase64Image", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64Image")
    @ResponseWrapper(localName = "signPdfBase64ImageResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64ImageResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfBase64ImageRequest", output = "http://ws.viettel.com/SignServerWS/signPdfBase64ImageResponse")
    public SignFileResponceBO signPdfBase64Image(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayImageConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfFilePathImage", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathImage")
    @ResponseWrapper(localName = "signPdfFilePathImageResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathImageResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfFilePathImageRequest", output = "http://ws.viettel.com/SignServerWS/signPdfFilePathImageResponse")
    public SignFileResponceBO signPdfFilePathImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayImageConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfBase64Table", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64Table")
    @ResponseWrapper(localName = "signPdfBase64TableResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfBase64TableResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfBase64TableRequest", output = "http://ws.viettel.com/SignServerWS/signPdfBase64TableResponse")
    public SignFileResponceBO signPdfBase64Table(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayTableConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns com.isofh.signer.viettel.ws.SignFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signPdfFilePathTable", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathTable")
    @ResponseWrapper(localName = "signPdfFilePathTableResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.SignPdfFilePathTableResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/signPdfFilePathTableRequest", output = "http://ws.viettel.com/SignServerWS/signPdfFilePathTableResponse")
    public SignFileResponceBO signPdfFilePathTable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DisplayTableConfigBO arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        TimestampConfig arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFilePdfBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFilePdfBase64")
    @ResponseWrapper(localName = "verifyFilePdfBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFilePdfBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFilePdfBase64Request", output = "http://ws.viettel.com/SignServerWS/verifyFilePdfBase64Response")
    public VerifyFileResponceBO verifyFilePdfBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFilePdfFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFilePdfFilePath")
    @ResponseWrapper(localName = "verifyFilePdfFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFilePdfFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFilePdfFilePathRequest", output = "http://ws.viettel.com/SignServerWS/verifyFilePdfFilePathResponse")
    public VerifyFileResponceBO verifyFilePdfFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFileXmlBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileXmlBase64")
    @ResponseWrapper(localName = "verifyFileXmlBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileXmlBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFileXmlBase64Request", output = "http://ws.viettel.com/SignServerWS/verifyFileXmlBase64Response")
    public VerifyFileResponceBO verifyFileXmlBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFileXmlFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileXmlFilePath")
    @ResponseWrapper(localName = "verifyFileXmlFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileXmlFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFileXmlFilePathRequest", output = "http://ws.viettel.com/SignServerWS/verifyFileXmlFilePathResponse")
    public VerifyFileResponceBO verifyFileXmlFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFileOOXmlBase64", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileOOXmlBase64")
    @ResponseWrapper(localName = "verifyFileOOXmlBase64Response", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileOOXmlBase64Response")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFileOOXmlBase64Request", output = "http://ws.viettel.com/SignServerWS/verifyFileOOXmlBase64Response")
    public VerifyFileResponceBO verifyFileOOXmlBase64(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.VerifyFileResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFileOOXmlFilePath", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileOOXmlFilePath")
    @ResponseWrapper(localName = "verifyFileOOXmlFilePathResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.VerifyFileOOXmlFilePathResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/verifyFileOOXmlFilePathRequest", output = "http://ws.viettel.com/SignServerWS/verifyFileOOXmlFilePathResponse")
    public VerifyFileResponceBO verifyFileOOXmlFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.isofh.signer.viettel.ws.CertListResponceBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertList", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.GetCertList")
    @ResponseWrapper(localName = "getCertListResponse", targetNamespace = "http://ws.viettel.com/", className = "com.isofh.signer.viettel.ws.GetCertListResponse")
    @Action(input = "http://ws.viettel.com/SignServerWS/getCertListRequest", output = "http://ws.viettel.com/SignServerWS/getCertListResponse")
    public CertListResponceBO getCertList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
