package com.isofh.hibernate.entities;
// Generated May 26, 2016 9:09:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdUser generated by hbm2java
 */
public class AdUser  implements java.io.Serializable {


     private long adUserId;
     private AdUser adUserBySupervisorId;
     private AdUser adUserBySalesrepId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String password;
     private String email;
     private Long CBpartnerId;
     private Character processing;
     private String emailuser;
     private String emailuserpw;
     private Long CBpartnerLocationId;
     private Long CGreetingId;
     private String title;
     private String comments;
     private String phone;
     private String phone2;
     private String fax;
     private Date lastcontact;
     private String lastresult;
     private Date birthday;
     private Long adOrgtrxId;
     private String emailverify;
     private Date emailverifydate;
     private char notificationtype;
     private char isfullbpaccess;
     private Long CJobId;
     private String ldapuser;
     private Character connectionprofile;
     private String value;
     private String userpin;
     private char isinpayroll;
     private String adUserUu;
     private Character ismenuautoexpand;
     private String salt;
     private char islocked;
     private Date dateaccountlocked;
     private long failedlogincount;
     private Date datepasswordchanged;
     private Date datelastlogin;
     private char isnopasswordreset;
     private char isexpired;
     private String securityquestion;
     private String answer;
     private char issaleslead;
     private Long CLocationId;
     private String leadsource;
     private String leadstatus;
     private String leadsourcedescription;
     private String leadstatusdescription;
     private Long CCampaignId;
     private String bpname;
     private Long bpLocationId;
     private char isaddmailtextautomatically;
     private Long RDefaultmailtextId;
     private BigDecimal hisPrescriptionLimit;
     private BigDecimal hisPrescriptionLimitExtra;
     private Long hisDepartmentId;
     private String accountno;
     private String fullname;
     private Long hisMajorId;
     private String hisPosition;
     private Long hisBuildingId;
     private Character isdoctor;
     private Character iscashier;
     private Long hisStorageId;
     private Long adminlevel;
     private Long hisStorageMedicineId;
     private Long hisStorageAccessoryId;
     private Long hisStorageChemicalId;
     private Long hisStorageBloodId;
     private String cashiersign;
     private Character isemergencycashier;
     private Set<AdUser> adUsersForSupervisorId = new HashSet<AdUser>(0);
     private Set<AdUser> adUsersForSalesrepId = new HashSet<AdUser>(0);

    public AdUser() {
    }

	
    public AdUser(long adUserId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char notificationtype, char isfullbpaccess, char isinpayroll, char islocked, long failedlogincount, char isnopasswordreset, char isexpired, char issaleslead, char isaddmailtextautomatically) {
        this.adUserId = adUserId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.notificationtype = notificationtype;
        this.isfullbpaccess = isfullbpaccess;
        this.isinpayroll = isinpayroll;
        this.islocked = islocked;
        this.failedlogincount = failedlogincount;
        this.isnopasswordreset = isnopasswordreset;
        this.isexpired = isexpired;
        this.issaleslead = issaleslead;
        this.isaddmailtextautomatically = isaddmailtextautomatically;
    }
    public AdUser(long adUserId, AdUser adUserBySupervisorId, AdUser adUserBySalesrepId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String password, String email, Long CBpartnerId, Character processing, String emailuser, String emailuserpw, Long CBpartnerLocationId, Long CGreetingId, String title, String comments, String phone, String phone2, String fax, Date lastcontact, String lastresult, Date birthday, Long adOrgtrxId, String emailverify, Date emailverifydate, char notificationtype, char isfullbpaccess, Long CJobId, String ldapuser, Character connectionprofile, String value, String userpin, char isinpayroll, String adUserUu, Character ismenuautoexpand, String salt, char islocked, Date dateaccountlocked, long failedlogincount, Date datepasswordchanged, Date datelastlogin, char isnopasswordreset, char isexpired, String securityquestion, String answer, char issaleslead, Long CLocationId, String leadsource, String leadstatus, String leadsourcedescription, String leadstatusdescription, Long CCampaignId, String bpname, Long bpLocationId, char isaddmailtextautomatically, Long RDefaultmailtextId, BigDecimal hisPrescriptionLimit, BigDecimal hisPrescriptionLimitExtra, Long hisDepartmentId, String accountno, String fullname, Long hisMajorId, String hisPosition, Long hisBuildingId, Character isdoctor, Character iscashier, Long hisStorageId, Long adminlevel, Long hisStorageMedicineId, Long hisStorageAccessoryId, Long hisStorageChemicalId, Long hisStorageBloodId, String cashiersign, Character isemergencycashier, Set<AdUser> adUsersForSupervisorId, Set<AdUser> adUsersForSalesrepId) {
       this.adUserId = adUserId;
       this.adUserBySupervisorId = adUserBySupervisorId;
       this.adUserBySalesrepId = adUserBySalesrepId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.password = password;
       this.email = email;
       this.CBpartnerId = CBpartnerId;
       this.processing = processing;
       this.emailuser = emailuser;
       this.emailuserpw = emailuserpw;
       this.CBpartnerLocationId = CBpartnerLocationId;
       this.CGreetingId = CGreetingId;
       this.title = title;
       this.comments = comments;
       this.phone = phone;
       this.phone2 = phone2;
       this.fax = fax;
       this.lastcontact = lastcontact;
       this.lastresult = lastresult;
       this.birthday = birthday;
       this.adOrgtrxId = adOrgtrxId;
       this.emailverify = emailverify;
       this.emailverifydate = emailverifydate;
       this.notificationtype = notificationtype;
       this.isfullbpaccess = isfullbpaccess;
       this.CJobId = CJobId;
       this.ldapuser = ldapuser;
       this.connectionprofile = connectionprofile;
       this.value = value;
       this.userpin = userpin;
       this.isinpayroll = isinpayroll;
       this.adUserUu = adUserUu;
       this.ismenuautoexpand = ismenuautoexpand;
       this.salt = salt;
       this.islocked = islocked;
       this.dateaccountlocked = dateaccountlocked;
       this.failedlogincount = failedlogincount;
       this.datepasswordchanged = datepasswordchanged;
       this.datelastlogin = datelastlogin;
       this.isnopasswordreset = isnopasswordreset;
       this.isexpired = isexpired;
       this.securityquestion = securityquestion;
       this.answer = answer;
       this.issaleslead = issaleslead;
       this.CLocationId = CLocationId;
       this.leadsource = leadsource;
       this.leadstatus = leadstatus;
       this.leadsourcedescription = leadsourcedescription;
       this.leadstatusdescription = leadstatusdescription;
       this.CCampaignId = CCampaignId;
       this.bpname = bpname;
       this.bpLocationId = bpLocationId;
       this.isaddmailtextautomatically = isaddmailtextautomatically;
       this.RDefaultmailtextId = RDefaultmailtextId;
       this.hisPrescriptionLimit = hisPrescriptionLimit;
       this.hisPrescriptionLimitExtra = hisPrescriptionLimitExtra;
       this.hisDepartmentId = hisDepartmentId;
       this.accountno = accountno;
       this.fullname = fullname;
       this.hisMajorId = hisMajorId;
       this.hisPosition = hisPosition;
       this.hisBuildingId = hisBuildingId;
       this.isdoctor = isdoctor;
       this.iscashier = iscashier;
       this.hisStorageId = hisStorageId;
       this.adminlevel = adminlevel;
       this.hisStorageMedicineId = hisStorageMedicineId;
       this.hisStorageAccessoryId = hisStorageAccessoryId;
       this.hisStorageChemicalId = hisStorageChemicalId;
       this.hisStorageBloodId = hisStorageBloodId;
       this.cashiersign = cashiersign;
       this.isemergencycashier = isemergencycashier;
       this.adUsersForSupervisorId = adUsersForSupervisorId;
       this.adUsersForSalesrepId = adUsersForSalesrepId;
    }
   
    public long getAdUserId() {
        return this.adUserId;
    }
    
    public void setAdUserId(long adUserId) {
        this.adUserId = adUserId;
    }
    public AdUser getAdUserBySupervisorId() {
        return this.adUserBySupervisorId;
    }
    
    public void setAdUserBySupervisorId(AdUser adUserBySupervisorId) {
        this.adUserBySupervisorId = adUserBySupervisorId;
    }
    public AdUser getAdUserBySalesrepId() {
        return this.adUserBySalesrepId;
    }
    
    public void setAdUserBySalesrepId(AdUser adUserBySalesrepId) {
        this.adUserBySalesrepId = adUserBySalesrepId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getCBpartnerId() {
        return this.CBpartnerId;
    }
    
    public void setCBpartnerId(Long CBpartnerId) {
        this.CBpartnerId = CBpartnerId;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public String getEmailuser() {
        return this.emailuser;
    }
    
    public void setEmailuser(String emailuser) {
        this.emailuser = emailuser;
    }
    public String getEmailuserpw() {
        return this.emailuserpw;
    }
    
    public void setEmailuserpw(String emailuserpw) {
        this.emailuserpw = emailuserpw;
    }
    public Long getCBpartnerLocationId() {
        return this.CBpartnerLocationId;
    }
    
    public void setCBpartnerLocationId(Long CBpartnerLocationId) {
        this.CBpartnerLocationId = CBpartnerLocationId;
    }
    public Long getCGreetingId() {
        return this.CGreetingId;
    }
    
    public void setCGreetingId(Long CGreetingId) {
        this.CGreetingId = CGreetingId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public Date getLastcontact() {
        return this.lastcontact;
    }
    
    public void setLastcontact(Date lastcontact) {
        this.lastcontact = lastcontact;
    }
    public String getLastresult() {
        return this.lastresult;
    }
    
    public void setLastresult(String lastresult) {
        this.lastresult = lastresult;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Long getAdOrgtrxId() {
        return this.adOrgtrxId;
    }
    
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }
    public String getEmailverify() {
        return this.emailverify;
    }
    
    public void setEmailverify(String emailverify) {
        this.emailverify = emailverify;
    }
    public Date getEmailverifydate() {
        return this.emailverifydate;
    }
    
    public void setEmailverifydate(Date emailverifydate) {
        this.emailverifydate = emailverifydate;
    }
    public char getNotificationtype() {
        return this.notificationtype;
    }
    
    public void setNotificationtype(char notificationtype) {
        this.notificationtype = notificationtype;
    }
    public char getIsfullbpaccess() {
        return this.isfullbpaccess;
    }
    
    public void setIsfullbpaccess(char isfullbpaccess) {
        this.isfullbpaccess = isfullbpaccess;
    }
    public Long getCJobId() {
        return this.CJobId;
    }
    
    public void setCJobId(Long CJobId) {
        this.CJobId = CJobId;
    }
    public String getLdapuser() {
        return this.ldapuser;
    }
    
    public void setLdapuser(String ldapuser) {
        this.ldapuser = ldapuser;
    }
    public Character getConnectionprofile() {
        return this.connectionprofile;
    }
    
    public void setConnectionprofile(Character connectionprofile) {
        this.connectionprofile = connectionprofile;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getUserpin() {
        return this.userpin;
    }
    
    public void setUserpin(String userpin) {
        this.userpin = userpin;
    }
    public char getIsinpayroll() {
        return this.isinpayroll;
    }
    
    public void setIsinpayroll(char isinpayroll) {
        this.isinpayroll = isinpayroll;
    }
    public String getAdUserUu() {
        return this.adUserUu;
    }
    
    public void setAdUserUu(String adUserUu) {
        this.adUserUu = adUserUu;
    }
    public Character getIsmenuautoexpand() {
        return this.ismenuautoexpand;
    }
    
    public void setIsmenuautoexpand(Character ismenuautoexpand) {
        this.ismenuautoexpand = ismenuautoexpand;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public char getIslocked() {
        return this.islocked;
    }
    
    public void setIslocked(char islocked) {
        this.islocked = islocked;
    }
    public Date getDateaccountlocked() {
        return this.dateaccountlocked;
    }
    
    public void setDateaccountlocked(Date dateaccountlocked) {
        this.dateaccountlocked = dateaccountlocked;
    }
    public long getFailedlogincount() {
        return this.failedlogincount;
    }
    
    public void setFailedlogincount(long failedlogincount) {
        this.failedlogincount = failedlogincount;
    }
    public Date getDatepasswordchanged() {
        return this.datepasswordchanged;
    }
    
    public void setDatepasswordchanged(Date datepasswordchanged) {
        this.datepasswordchanged = datepasswordchanged;
    }
    public Date getDatelastlogin() {
        return this.datelastlogin;
    }
    
    public void setDatelastlogin(Date datelastlogin) {
        this.datelastlogin = datelastlogin;
    }
    public char getIsnopasswordreset() {
        return this.isnopasswordreset;
    }
    
    public void setIsnopasswordreset(char isnopasswordreset) {
        this.isnopasswordreset = isnopasswordreset;
    }
    public char getIsexpired() {
        return this.isexpired;
    }
    
    public void setIsexpired(char isexpired) {
        this.isexpired = isexpired;
    }
    public String getSecurityquestion() {
        return this.securityquestion;
    }
    
    public void setSecurityquestion(String securityquestion) {
        this.securityquestion = securityquestion;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public char getIssaleslead() {
        return this.issaleslead;
    }
    
    public void setIssaleslead(char issaleslead) {
        this.issaleslead = issaleslead;
    }
    public Long getCLocationId() {
        return this.CLocationId;
    }
    
    public void setCLocationId(Long CLocationId) {
        this.CLocationId = CLocationId;
    }
    public String getLeadsource() {
        return this.leadsource;
    }
    
    public void setLeadsource(String leadsource) {
        this.leadsource = leadsource;
    }
    public String getLeadstatus() {
        return this.leadstatus;
    }
    
    public void setLeadstatus(String leadstatus) {
        this.leadstatus = leadstatus;
    }
    public String getLeadsourcedescription() {
        return this.leadsourcedescription;
    }
    
    public void setLeadsourcedescription(String leadsourcedescription) {
        this.leadsourcedescription = leadsourcedescription;
    }
    public String getLeadstatusdescription() {
        return this.leadstatusdescription;
    }
    
    public void setLeadstatusdescription(String leadstatusdescription) {
        this.leadstatusdescription = leadstatusdescription;
    }
    public Long getCCampaignId() {
        return this.CCampaignId;
    }
    
    public void setCCampaignId(Long CCampaignId) {
        this.CCampaignId = CCampaignId;
    }
    public String getBpname() {
        return this.bpname;
    }
    
    public void setBpname(String bpname) {
        this.bpname = bpname;
    }
    public Long getBpLocationId() {
        return this.bpLocationId;
    }
    
    public void setBpLocationId(Long bpLocationId) {
        this.bpLocationId = bpLocationId;
    }
    public char getIsaddmailtextautomatically() {
        return this.isaddmailtextautomatically;
    }
    
    public void setIsaddmailtextautomatically(char isaddmailtextautomatically) {
        this.isaddmailtextautomatically = isaddmailtextautomatically;
    }
    public Long getRDefaultmailtextId() {
        return this.RDefaultmailtextId;
    }
    
    public void setRDefaultmailtextId(Long RDefaultmailtextId) {
        this.RDefaultmailtextId = RDefaultmailtextId;
    }
    public BigDecimal getHisPrescriptionLimit() {
        return this.hisPrescriptionLimit;
    }
    
    public void setHisPrescriptionLimit(BigDecimal hisPrescriptionLimit) {
        this.hisPrescriptionLimit = hisPrescriptionLimit;
    }
    public BigDecimal getHisPrescriptionLimitExtra() {
        return this.hisPrescriptionLimitExtra;
    }
    
    public void setHisPrescriptionLimitExtra(BigDecimal hisPrescriptionLimitExtra) {
        this.hisPrescriptionLimitExtra = hisPrescriptionLimitExtra;
    }
    public Long getHisDepartmentId() {
        return this.hisDepartmentId;
    }
    
    public void setHisDepartmentId(Long hisDepartmentId) {
        this.hisDepartmentId = hisDepartmentId;
    }
    public String getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Long getHisMajorId() {
        return this.hisMajorId;
    }
    
    public void setHisMajorId(Long hisMajorId) {
        this.hisMajorId = hisMajorId;
    }
    public String getHisPosition() {
        return this.hisPosition;
    }
    
    public void setHisPosition(String hisPosition) {
        this.hisPosition = hisPosition;
    }
    public Long getHisBuildingId() {
        return this.hisBuildingId;
    }
    
    public void setHisBuildingId(Long hisBuildingId) {
        this.hisBuildingId = hisBuildingId;
    }
    public Character getIsdoctor() {
        return this.isdoctor;
    }
    
    public void setIsdoctor(Character isdoctor) {
        this.isdoctor = isdoctor;
    }
    public Character getIscashier() {
        return this.iscashier;
    }
    
    public void setIscashier(Character iscashier) {
        this.iscashier = iscashier;
    }
    public Long getHisStorageId() {
        return this.hisStorageId;
    }
    
    public void setHisStorageId(Long hisStorageId) {
        this.hisStorageId = hisStorageId;
    }
    public Long getAdminlevel() {
        return this.adminlevel;
    }
    
    public void setAdminlevel(Long adminlevel) {
        this.adminlevel = adminlevel;
    }
    public Long getHisStorageMedicineId() {
        return this.hisStorageMedicineId;
    }
    
    public void setHisStorageMedicineId(Long hisStorageMedicineId) {
        this.hisStorageMedicineId = hisStorageMedicineId;
    }
    public Long getHisStorageAccessoryId() {
        return this.hisStorageAccessoryId;
    }
    
    public void setHisStorageAccessoryId(Long hisStorageAccessoryId) {
        this.hisStorageAccessoryId = hisStorageAccessoryId;
    }
    public Long getHisStorageChemicalId() {
        return this.hisStorageChemicalId;
    }
    
    public void setHisStorageChemicalId(Long hisStorageChemicalId) {
        this.hisStorageChemicalId = hisStorageChemicalId;
    }
    public Long getHisStorageBloodId() {
        return this.hisStorageBloodId;
    }
    
    public void setHisStorageBloodId(Long hisStorageBloodId) {
        this.hisStorageBloodId = hisStorageBloodId;
    }
    public String getCashiersign() {
        return this.cashiersign;
    }
    
    public void setCashiersign(String cashiersign) {
        this.cashiersign = cashiersign;
    }
    public Character getIsemergencycashier() {
        return this.isemergencycashier;
    }
    
    public void setIsemergencycashier(Character isemergencycashier) {
        this.isemergencycashier = isemergencycashier;
    }
    public Set<AdUser> getAdUsersForSupervisorId() {
        return this.adUsersForSupervisorId;
    }
    
    public void setAdUsersForSupervisorId(Set<AdUser> adUsersForSupervisorId) {
        this.adUsersForSupervisorId = adUsersForSupervisorId;
    }
    public Set<AdUser> getAdUsersForSalesrepId() {
        return this.adUsersForSalesrepId;
    }
    
    public void setAdUsersForSalesrepId(Set<AdUser> adUsersForSalesrepId) {
        this.adUsersForSalesrepId = adUsersForSalesrepId;
    }




}


