package com.isofh.hibernate.entities;
// Generated May 26, 2016 9:09:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HisMedicaltest generated by hbm2java
 */
public class HisMedicaltest  implements java.io.Serializable {


     private long hisMedicaltestId;
     private Long adClientId;
     private Long adOrgId;
     private Long CUomId;
     private Date created;
     private Long createdby;
     private String englishname;
     private String femalehighindicator;
     private String femalelowindicator;
     private String hisMedicaltestUu;
     private Long hisRoomId;
     private long hisServicegrouplevel1Id;
     private Long hisServicegrouplevel2Id;
     private Long hisServicegrouplevel3Id;
     private String hisServicetype;
     private Character isactive;
     private Character ishightech;
     private Character isincomereport;
     private Character isinpatient;
     private Character isinputquantity;
     private Character isoutpatient;
     private String malehighindicator;
     private String malelowindicator;
     private String name;
     private BigDecimal priceassurance;
     private BigDecimal pricediff;
     private BigDecimal priceservice;
     private String shortname;
     private String tag1;
     private Date updated;
     private Long updatedby;
     private Character useinreception;
     private String value;
     private String tag2;
     private String hisLisCode;
     private BigDecimal assurancequota;
     private String conclusiontemplate;
     private String hisCheckupType;
     private Long hisMedicineId;
     private Long hisSpecialistId;
     private String requiredticket;
     private String resulttemplate;
     private String templateid;
     private String unit;
     private Long hisDepartmentId;
     private Character isinpackage;
     private Character istimekeeping;
     private String note37;
     private Character isserviceinhospital;
     private Long hisServiceId;
     private String reporttemplatevalue;
     private Long hisReporttemplateId;
     private String unitprint;
     private String higherindicator;
     private String lowerindicator;
     private long printorder;
     private String hisSurgeryformId;

    public HisMedicaltest() {
    }

	
    public HisMedicaltest(long hisMedicaltestId, long hisServicegrouplevel1Id, String hisServicetype, BigDecimal priceservice, long printorder) {
        this.hisMedicaltestId = hisMedicaltestId;
        this.hisServicegrouplevel1Id = hisServicegrouplevel1Id;
        this.hisServicetype = hisServicetype;
        this.priceservice = priceservice;
        this.printorder = printorder;
    }
    public HisMedicaltest(long hisMedicaltestId, Long adClientId, Long adOrgId, Long CUomId, Date created, Long createdby, String englishname, String femalehighindicator, String femalelowindicator, String hisMedicaltestUu, Long hisRoomId, long hisServicegrouplevel1Id, Long hisServicegrouplevel2Id, Long hisServicegrouplevel3Id, String hisServicetype, Character isactive, Character ishightech, Character isincomereport, Character isinpatient, Character isinputquantity, Character isoutpatient, String malehighindicator, String malelowindicator, String name, BigDecimal priceassurance, BigDecimal pricediff, BigDecimal priceservice, String shortname, String tag1, Date updated, Long updatedby, Character useinreception, String value, String tag2, String hisLisCode, BigDecimal assurancequota, String conclusiontemplate, String hisCheckupType, Long hisMedicineId, Long hisSpecialistId, String requiredticket, String resulttemplate, String templateid, String unit, Long hisDepartmentId, Character isinpackage, Character istimekeeping, String note37, Character isserviceinhospital, Long hisServiceId, String reporttemplatevalue, Long hisReporttemplateId, String unitprint, String higherindicator, String lowerindicator, long printorder, String hisSurgeryformId) {
       this.hisMedicaltestId = hisMedicaltestId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.CUomId = CUomId;
       this.created = created;
       this.createdby = createdby;
       this.englishname = englishname;
       this.femalehighindicator = femalehighindicator;
       this.femalelowindicator = femalelowindicator;
       this.hisMedicaltestUu = hisMedicaltestUu;
       this.hisRoomId = hisRoomId;
       this.hisServicegrouplevel1Id = hisServicegrouplevel1Id;
       this.hisServicegrouplevel2Id = hisServicegrouplevel2Id;
       this.hisServicegrouplevel3Id = hisServicegrouplevel3Id;
       this.hisServicetype = hisServicetype;
       this.isactive = isactive;
       this.ishightech = ishightech;
       this.isincomereport = isincomereport;
       this.isinpatient = isinpatient;
       this.isinputquantity = isinputquantity;
       this.isoutpatient = isoutpatient;
       this.malehighindicator = malehighindicator;
       this.malelowindicator = malelowindicator;
       this.name = name;
       this.priceassurance = priceassurance;
       this.pricediff = pricediff;
       this.priceservice = priceservice;
       this.shortname = shortname;
       this.tag1 = tag1;
       this.updated = updated;
       this.updatedby = updatedby;
       this.useinreception = useinreception;
       this.value = value;
       this.tag2 = tag2;
       this.hisLisCode = hisLisCode;
       this.assurancequota = assurancequota;
       this.conclusiontemplate = conclusiontemplate;
       this.hisCheckupType = hisCheckupType;
       this.hisMedicineId = hisMedicineId;
       this.hisSpecialistId = hisSpecialistId;
       this.requiredticket = requiredticket;
       this.resulttemplate = resulttemplate;
       this.templateid = templateid;
       this.unit = unit;
       this.hisDepartmentId = hisDepartmentId;
       this.isinpackage = isinpackage;
       this.istimekeeping = istimekeeping;
       this.note37 = note37;
       this.isserviceinhospital = isserviceinhospital;
       this.hisServiceId = hisServiceId;
       this.reporttemplatevalue = reporttemplatevalue;
       this.hisReporttemplateId = hisReporttemplateId;
       this.unitprint = unitprint;
       this.higherindicator = higherindicator;
       this.lowerindicator = lowerindicator;
       this.printorder = printorder;
       this.hisSurgeryformId = hisSurgeryformId;
    }
   
    public long getHisMedicaltestId() {
        return this.hisMedicaltestId;
    }
    
    public void setHisMedicaltestId(long hisMedicaltestId) {
        this.hisMedicaltestId = hisMedicaltestId;
    }
    public Long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(Long adClientId) {
        this.adClientId = adClientId;
    }
    public Long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(Long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public Long getCUomId() {
        return this.CUomId;
    }
    
    public void setCUomId(Long CUomId) {
        this.CUomId = CUomId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }
    public String getEnglishname() {
        return this.englishname;
    }
    
    public void setEnglishname(String englishname) {
        this.englishname = englishname;
    }
    public String getFemalehighindicator() {
        return this.femalehighindicator;
    }
    
    public void setFemalehighindicator(String femalehighindicator) {
        this.femalehighindicator = femalehighindicator;
    }
    public String getFemalelowindicator() {
        return this.femalelowindicator;
    }
    
    public void setFemalelowindicator(String femalelowindicator) {
        this.femalelowindicator = femalelowindicator;
    }
    public String getHisMedicaltestUu() {
        return this.hisMedicaltestUu;
    }
    
    public void setHisMedicaltestUu(String hisMedicaltestUu) {
        this.hisMedicaltestUu = hisMedicaltestUu;
    }
    public Long getHisRoomId() {
        return this.hisRoomId;
    }
    
    public void setHisRoomId(Long hisRoomId) {
        this.hisRoomId = hisRoomId;
    }
    public long getHisServicegrouplevel1Id() {
        return this.hisServicegrouplevel1Id;
    }
    
    public void setHisServicegrouplevel1Id(long hisServicegrouplevel1Id) {
        this.hisServicegrouplevel1Id = hisServicegrouplevel1Id;
    }
    public Long getHisServicegrouplevel2Id() {
        return this.hisServicegrouplevel2Id;
    }
    
    public void setHisServicegrouplevel2Id(Long hisServicegrouplevel2Id) {
        this.hisServicegrouplevel2Id = hisServicegrouplevel2Id;
    }
    public Long getHisServicegrouplevel3Id() {
        return this.hisServicegrouplevel3Id;
    }
    
    public void setHisServicegrouplevel3Id(Long hisServicegrouplevel3Id) {
        this.hisServicegrouplevel3Id = hisServicegrouplevel3Id;
    }
    public String getHisServicetype() {
        return this.hisServicetype;
    }
    
    public void setHisServicetype(String hisServicetype) {
        this.hisServicetype = hisServicetype;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public Character getIshightech() {
        return this.ishightech;
    }
    
    public void setIshightech(Character ishightech) {
        this.ishightech = ishightech;
    }
    public Character getIsincomereport() {
        return this.isincomereport;
    }
    
    public void setIsincomereport(Character isincomereport) {
        this.isincomereport = isincomereport;
    }
    public Character getIsinpatient() {
        return this.isinpatient;
    }
    
    public void setIsinpatient(Character isinpatient) {
        this.isinpatient = isinpatient;
    }
    public Character getIsinputquantity() {
        return this.isinputquantity;
    }
    
    public void setIsinputquantity(Character isinputquantity) {
        this.isinputquantity = isinputquantity;
    }
    public Character getIsoutpatient() {
        return this.isoutpatient;
    }
    
    public void setIsoutpatient(Character isoutpatient) {
        this.isoutpatient = isoutpatient;
    }
    public String getMalehighindicator() {
        return this.malehighindicator;
    }
    
    public void setMalehighindicator(String malehighindicator) {
        this.malehighindicator = malehighindicator;
    }
    public String getMalelowindicator() {
        return this.malelowindicator;
    }
    
    public void setMalelowindicator(String malelowindicator) {
        this.malelowindicator = malelowindicator;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPriceassurance() {
        return this.priceassurance;
    }
    
    public void setPriceassurance(BigDecimal priceassurance) {
        this.priceassurance = priceassurance;
    }
    public BigDecimal getPricediff() {
        return this.pricediff;
    }
    
    public void setPricediff(BigDecimal pricediff) {
        this.pricediff = pricediff;
    }
    public BigDecimal getPriceservice() {
        return this.priceservice;
    }
    
    public void setPriceservice(BigDecimal priceservice) {
        this.priceservice = priceservice;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getTag1() {
        return this.tag1;
    }
    
    public void setTag1(String tag1) {
        this.tag1 = tag1;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(Long updatedby) {
        this.updatedby = updatedby;
    }
    public Character getUseinreception() {
        return this.useinreception;
    }
    
    public void setUseinreception(Character useinreception) {
        this.useinreception = useinreception;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getTag2() {
        return this.tag2;
    }
    
    public void setTag2(String tag2) {
        this.tag2 = tag2;
    }
    public String getHisLisCode() {
        return this.hisLisCode;
    }
    
    public void setHisLisCode(String hisLisCode) {
        this.hisLisCode = hisLisCode;
    }
    public BigDecimal getAssurancequota() {
        return this.assurancequota;
    }
    
    public void setAssurancequota(BigDecimal assurancequota) {
        this.assurancequota = assurancequota;
    }
    public String getConclusiontemplate() {
        return this.conclusiontemplate;
    }
    
    public void setConclusiontemplate(String conclusiontemplate) {
        this.conclusiontemplate = conclusiontemplate;
    }
    public String getHisCheckupType() {
        return this.hisCheckupType;
    }
    
    public void setHisCheckupType(String hisCheckupType) {
        this.hisCheckupType = hisCheckupType;
    }
    public Long getHisMedicineId() {
        return this.hisMedicineId;
    }
    
    public void setHisMedicineId(Long hisMedicineId) {
        this.hisMedicineId = hisMedicineId;
    }
    public Long getHisSpecialistId() {
        return this.hisSpecialistId;
    }
    
    public void setHisSpecialistId(Long hisSpecialistId) {
        this.hisSpecialistId = hisSpecialistId;
    }
    public String getRequiredticket() {
        return this.requiredticket;
    }
    
    public void setRequiredticket(String requiredticket) {
        this.requiredticket = requiredticket;
    }
    public String getResulttemplate() {
        return this.resulttemplate;
    }
    
    public void setResulttemplate(String resulttemplate) {
        this.resulttemplate = resulttemplate;
    }
    public String getTemplateid() {
        return this.templateid;
    }
    
    public void setTemplateid(String templateid) {
        this.templateid = templateid;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Long getHisDepartmentId() {
        return this.hisDepartmentId;
    }
    
    public void setHisDepartmentId(Long hisDepartmentId) {
        this.hisDepartmentId = hisDepartmentId;
    }
    public Character getIsinpackage() {
        return this.isinpackage;
    }
    
    public void setIsinpackage(Character isinpackage) {
        this.isinpackage = isinpackage;
    }
    public Character getIstimekeeping() {
        return this.istimekeeping;
    }
    
    public void setIstimekeeping(Character istimekeeping) {
        this.istimekeeping = istimekeeping;
    }
    public String getNote37() {
        return this.note37;
    }
    
    public void setNote37(String note37) {
        this.note37 = note37;
    }
    public Character getIsserviceinhospital() {
        return this.isserviceinhospital;
    }
    
    public void setIsserviceinhospital(Character isserviceinhospital) {
        this.isserviceinhospital = isserviceinhospital;
    }
    public Long getHisServiceId() {
        return this.hisServiceId;
    }
    
    public void setHisServiceId(Long hisServiceId) {
        this.hisServiceId = hisServiceId;
    }
    public String getReporttemplatevalue() {
        return this.reporttemplatevalue;
    }
    
    public void setReporttemplatevalue(String reporttemplatevalue) {
        this.reporttemplatevalue = reporttemplatevalue;
    }
    public Long getHisReporttemplateId() {
        return this.hisReporttemplateId;
    }
    
    public void setHisReporttemplateId(Long hisReporttemplateId) {
        this.hisReporttemplateId = hisReporttemplateId;
    }
    public String getUnitprint() {
        return this.unitprint;
    }
    
    public void setUnitprint(String unitprint) {
        this.unitprint = unitprint;
    }
    public String getHigherindicator() {
        return this.higherindicator;
    }
    
    public void setHigherindicator(String higherindicator) {
        this.higherindicator = higherindicator;
    }
    public String getLowerindicator() {
        return this.lowerindicator;
    }
    
    public void setLowerindicator(String lowerindicator) {
        this.lowerindicator = lowerindicator;
    }
    public long getPrintorder() {
        return this.printorder;
    }
    
    public void setPrintorder(long printorder) {
        this.printorder = printorder;
    }
    public String getHisSurgeryformId() {
        return this.hisSurgeryformId;
    }
    
    public void setHisSurgeryformId(String hisSurgeryformId) {
        this.hisSurgeryformId = hisSurgeryformId;
    }




}


