package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 4:51:39 PM by Hibernate Tools 4.3.1

import java.util.Date;


/**
 * HisServiceMedictestline generated by hbm2java
 */
public class HisServiceMedictestLine  implements java.io.Serializable {


     private int serviceMedicaltestLineID;
     private int medicaltestLineID;
     private int serviceMedicaltestID;
     private int patientHistoryID;
     private String indicatorStr;
     private Date updated;
     private int updatedBy;

    public HisServiceMedictestLine() {
    }

    public int getServiceMedicaltestLineID() {
        return serviceMedicaltestLineID;
    }

    public void setServiceMedicaltestLineID(int serviceMedicaltestLineID) {
        this.serviceMedicaltestLineID = serviceMedicaltestLineID;
    }

    public int getMedicaltestLineID() {
        return medicaltestLineID;
    }

    public void setMedicaltestLineID(int medicaltestLineID) {
        this.medicaltestLineID = medicaltestLineID;
    }

    public int getServiceMedicaltestID() {
        return serviceMedicaltestID;
    }

    public void setServiceMedicaltestID(int serviceMedicaltestID) {
        this.serviceMedicaltestID = serviceMedicaltestID;
    }

    public int getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(int patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }

    public String getIndicatorStr() {
        return indicatorStr;
    }

    public void setIndicatorStr(String indicatorStr) {
        this.indicatorStr = indicatorStr;
    }

    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public int getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    
    
}


