package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 4:51:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HisServiceMedicaltest generated by hbm2java
 */
public class HisServiceMedicaltest  implements java.io.Serializable {


     private int serviceMedicaltestID;
     private String status;
     private Date timegotResult;
     private Date timehasResult;
     private Date timeTakePatient;
     private Date updated;
     private int updatedby;
     private int serviceMedictestGroupID;
     private String patientValue;
     private String patientMedicalRecordNo;
     private String indicatorStr;
     private int patientHistoryID;

    public HisServiceMedicaltest() {
    }

    public int getServiceMedicaltestID() {
        return serviceMedicaltestID;
    }

    public void setServiceMedicaltestID(int serviceMedicaltestID) {
        this.serviceMedicaltestID = serviceMedicaltestID;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getTimegotResult() {
        return timegotResult;
    }

    public void setTimegotResult(Date timegotResult) {
        this.timegotResult = timegotResult;
    }

    public Date getTimehasResult() {
        return timehasResult;
    }

    public void setTimehasResult(Date timehasResult) {
        this.timehasResult = timehasResult;
    }

    public Date getTimeTakePatient() {
        return timeTakePatient;
    }

    public void setTimeTakePatient(Date timeTakePatient) {
        this.timeTakePatient = timeTakePatient;
    }

    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public int getUpdatedby() {
        return updatedby;
    }

    public void setUpdatedby(int updatedby) {
        this.updatedby = updatedby;
    }

    public int getServiceMedictestGroupID() {
        return serviceMedictestGroupID;
    }

    public void setServiceMedictestGroupID(int serviceMedictestGroupID) {
        this.serviceMedictestGroupID = serviceMedictestGroupID;
    }

    public String getPatientValue() {
        return patientValue;
    }

    public void setPatientValue(String patientValue) {
        this.patientValue = patientValue;
    }

    public String getPatientMedicalRecordNo() {
        return patientMedicalRecordNo;
    }

    public void setPatientMedicalRecordNo(String patientMedicalRecordNo) {
        this.patientMedicalRecordNo = patientMedicalRecordNo;
    }

    public String getIndicatorStr() {
        return indicatorStr;
    }

    public void setIndicatorStr(String indicatorStr) {
        this.indicatorStr = indicatorStr;
    }

    public int getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(int patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }
     
     
}


