package com.isofh.hibernate.entities;
// Generated Jun 2, 2016 11:45:36 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HisServiceMedictestline generated by hbm2java
 */
public class HisServiceMedictestline  implements java.io.Serializable {


     private long hisServiceMedictestlineId;
     private Long adClientId;
     private Long adOrgId;
     private Long CUomId;
     private String conclusion;
     private Date created;
     private Long createdby;
     private Long hisMedicaltestlineId;
     private Long hisRoomId;
     private Long hisServiceMedicaltestId;
     private BigDecimal indicator;
     private Character isactive;
     private Character iscomplete;
     private Character isready;
     private BigDecimal quantity;
     private Date updated;
     private Long updatedby;
     private String value;
     private Long hisPatienthistoryId;
     private String indicatorStr;

    public HisServiceMedictestline() {
    }

	
    public HisServiceMedictestline(long hisServiceMedictestlineId, BigDecimal indicator) {
        this.hisServiceMedictestlineId = hisServiceMedictestlineId;
        this.indicator = indicator;
    }
    public HisServiceMedictestline(long hisServiceMedictestlineId, Long adClientId, Long adOrgId, Long CUomId, String conclusion, Date created, Long createdby, Long hisMedicaltestlineId, Long hisRoomId, Long hisServiceMedicaltestId, BigDecimal indicator, Character isactive, Character iscomplete, Character isready, BigDecimal quantity, Date updated, Long updatedby, String value, Long hisPatienthistoryId, String indicatorStr) {
       this.hisServiceMedictestlineId = hisServiceMedictestlineId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.CUomId = CUomId;
       this.conclusion = conclusion;
       this.created = created;
       this.createdby = createdby;
       this.hisMedicaltestlineId = hisMedicaltestlineId;
       this.hisRoomId = hisRoomId;
       this.hisServiceMedicaltestId = hisServiceMedicaltestId;
       this.indicator = indicator;
       this.isactive = isactive;
       this.iscomplete = iscomplete;
       this.isready = isready;
       this.quantity = quantity;
       this.updated = updated;
       this.updatedby = updatedby;
       this.value = value;
       this.hisPatienthistoryId = hisPatienthistoryId;
       this.indicatorStr = indicatorStr;
    }
   
    public long getHisServiceMedictestlineId() {
        return this.hisServiceMedictestlineId;
    }
    
    public void setHisServiceMedictestlineId(long hisServiceMedictestlineId) {
        this.hisServiceMedictestlineId = hisServiceMedictestlineId;
    }
    public Long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(Long adClientId) {
        this.adClientId = adClientId;
    }
    public Long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(Long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public Long getCUomId() {
        return this.CUomId;
    }
    
    public void setCUomId(Long CUomId) {
        this.CUomId = CUomId;
    }
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }
    public Long getHisMedicaltestlineId() {
        return this.hisMedicaltestlineId;
    }
    
    public void setHisMedicaltestlineId(Long hisMedicaltestlineId) {
        this.hisMedicaltestlineId = hisMedicaltestlineId;
    }
    public Long getHisRoomId() {
        return this.hisRoomId;
    }
    
    public void setHisRoomId(Long hisRoomId) {
        this.hisRoomId = hisRoomId;
    }
    public Long getHisServiceMedicaltestId() {
        return this.hisServiceMedicaltestId;
    }
    
    public void setHisServiceMedicaltestId(Long hisServiceMedicaltestId) {
        this.hisServiceMedicaltestId = hisServiceMedicaltestId;
    }
    public BigDecimal getIndicator() {
        return this.indicator;
    }
    
    public void setIndicator(BigDecimal indicator) {
        this.indicator = indicator;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public Character getIscomplete() {
        return this.iscomplete;
    }
    
    public void setIscomplete(Character iscomplete) {
        this.iscomplete = iscomplete;
    }
    public Character getIsready() {
        return this.isready;
    }
    
    public void setIsready(Character isready) {
        this.isready = isready;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(Long updatedby) {
        this.updatedby = updatedby;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Long getHisPatienthistoryId() {
        return this.hisPatienthistoryId;
    }
    
    public void setHisPatienthistoryId(Long hisPatienthistoryId) {
        this.hisPatienthistoryId = hisPatienthistoryId;
    }
    public String getIndicatorStr() {
        return this.indicatorStr;
    }
    
    public void setIndicatorStr(String indicatorStr) {
        this.indicatorStr = indicatorStr;
    }




}


