package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 3:57:44 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * HisRvLisMedicaltestLpId generated by hbm2java
 */
public class RVServiceMedicaltest implements java.io.Serializable {
    private Date created;
    private Integer createdby;
    private String status;
    private String statusLis;
    private Date actdate;
    private String hisLisCode;
    private Integer patientHistoryID;
    private Integer serviceID;
    private Integer serviceMedicalTestID;
    private Integer roomID;
    private String room;
    private String roomValue;
    private Character isInpatient;
    private Integer medicaltestID;
    private Character isEmergency;
    private Integer diseaseDiagnosticID;
    private String fromDepartment;
    private Integer fromDepartmentID;
    private Integer departmentID;
    private String diseaseiagnostic;
    private Integer checkupUserID;
    private String checkupUserName;
    private Integer serviceMedictestGroupID;

    public RVServiceMedicaltest() {
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Integer getCreatedby() {
        return createdby;
    }

    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatusLis() {
        return statusLis;
    }

    public void setStatusLis(String statusLis) {
        this.statusLis = statusLis;
    }

    public Date getActdate() {
        return actdate;
    }

    public void setActdate(Date actdate) {
        this.actdate = actdate;
    }

    public String getHisLisCode() {
        return hisLisCode;
    }

    public void setHisLisCode(String hisLisCode) {
        this.hisLisCode = hisLisCode;
    }

    public Integer getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(Integer patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }

    public Integer getServiceID() {
        return serviceID;
    }

    public void setServiceID(Integer serviceID) {
        this.serviceID = serviceID;
    }

    public Integer getServiceMedicalTestID() {
        return serviceMedicalTestID;
    }

    public void setServiceMedicalTestID(Integer serviceMedicalTestID) {
        this.serviceMedicalTestID = serviceMedicalTestID;
    }

    public Integer getRoomID() {
        return roomID;
    }

    public void setRoomID(Integer roomID) {
        this.roomID = roomID;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getRoomValue() {
        return roomValue;
    }

    public void setRoomValue(String roomValue) {
        this.roomValue = roomValue;
    }

    public Character getIsInpatient() {
        return isInpatient;
    }

    public void setIsInpatient(Character isInpatient) {
        this.isInpatient = isInpatient;
    }

    public Integer getMedicaltestID() {
        return medicaltestID;
    }

    public void setMedicaltestID(Integer medicaltestID) {
        this.medicaltestID = medicaltestID;
    }

    public Character getIsEmergency() {
        return isEmergency;
    }

    public void setIsEmergency(Character isEmergency) {
        this.isEmergency = isEmergency;
    }

    public Integer getDiseaseDiagnosticID() {
        return diseaseDiagnosticID;
    }

    public void setDiseaseDiagnosticID(Integer diseaseDiagnosticID) {
        this.diseaseDiagnosticID = diseaseDiagnosticID;
    }

    public String getFromDepartment() {
        return fromDepartment;
    }

    public void setFromDepartment(String fromDepartment) {
        this.fromDepartment = fromDepartment;
    }

    public Integer getFromDepartmentID() {
        return fromDepartmentID;
    }

    public void setFromDepartmentID(Integer fromDepartmentID) {
        this.fromDepartmentID = fromDepartmentID;
    }

    public Integer getDepartmentID() {
        return departmentID;
    }

    public void setDepartmentID(Integer departmentID) {
        this.departmentID = departmentID;
    }

    public String getDiseaseiagnostic() {
        return diseaseiagnostic;
    }

    public void setDiseaseiagnostic(String diseaseiagnostic) {
        this.diseaseiagnostic = diseaseiagnostic;
    }

    public Integer getCheckupUserID() {
        return checkupUserID;
    }

    public void setCheckupUserID(Integer checkupUserID) {
        this.checkupUserID = checkupUserID;
    }

    public String getCheckupUserName() {
        return checkupUserName;
    }

    public void setCheckupUserName(String checkupUserName) {
        this.checkupUserName = checkupUserName;
    }

    public Integer getServiceMedictestGroupID() {
        return serviceMedictestGroupID;
    }

    public void setServiceMedictestGroupID(Integer serviceMedictestGroupID) {
        this.serviceMedictestGroupID = serviceMedictestGroupID;
    }

    


   

   
}
