package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 4:51:39 PM by Hibernate Tools 4.3.1

/**
 * HisServiceMedictestline generated by hbm2java
 */
public class RVServiceMedictestLine implements java.io.Serializable {

    private int serviceMedicaltestLineID;
    private int serviceMedicaltestID;
    private String hisLISCode;
    private int patientHistoryID;

    public RVServiceMedictestLine() {
    }

    public int getServiceMedicaltestLineID() {
        return serviceMedicaltestLineID;
    }

    public void setServiceMedicaltestLineID(int serviceMedicaltestLineID) {
        this.serviceMedicaltestLineID = serviceMedicaltestLineID;
    }

    public int getServiceMedicaltestID() {
        return serviceMedicaltestID;
    }

    public void setServiceMedicaltestID(int serviceMedicaltestID) {
        this.serviceMedicaltestID = serviceMedicaltestID;
    }

    public String getHisLISCode() {
        return hisLISCode;
    }

    public void setHisLISCode(String hisLISCode) {
        this.hisLISCode = hisLISCode;
    }

    public int getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(int patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }

}
