package com.isofh.hibernate.entities;
// Generated Jun 3, 2016 4:51:39 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;



/**
 * HisServiceMedictestline generated by hbm2java
 */
public class SeviceMedicaltestLine  implements java.io.Serializable {

     private int medicaltestLineID;
     private String HIS_LIS_Code;
     private int serviceMedicaltestLineID;
     private int serviceMedicaltestID;
     private Timestamp updated;
     private int updatedBy;
     private int patientHistoryID;
     private String indicatorStr;

    public SeviceMedicaltestLine() {
    }

    public int getMedicaltestLineID() {
        return medicaltestLineID;
    }

    public void setMedicaltestLineID(int medicaltestLineID) {
        this.medicaltestLineID = medicaltestLineID;
    }

    public String getHIS_LIS_Code() {
        return HIS_LIS_Code;
    }

    public void setHIS_LIS_Code(String HIS_LIS_Code) {
        this.HIS_LIS_Code = HIS_LIS_Code;
    }

    public int getServiceMedicaltestLineID() {
        return serviceMedicaltestLineID;
    }

    public void setServiceMedicaltestLineID(int serviceMedicaltestLineID) {
        this.serviceMedicaltestLineID = serviceMedicaltestLineID;
    }

    public int getServiceMedicaltestID() {
        return serviceMedicaltestID;
    }

    public void setServiceMedicaltestID(int serviceMedicaltestID) {
        this.serviceMedicaltestID = serviceMedicaltestID;
    }

    public Timestamp getUpdated() {
        return updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    public int getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }

    public int getPatientHistoryID() {
        return patientHistoryID;
    }

    public void setPatientHistoryID(int patientHistoryID) {
        this.patientHistoryID = patientHistoryID;
    }

    public String getIndicatorStr() {
        return indicatorStr;
    }

    public void setIndicatorStr(String indicatorStr) {
        this.indicatorStr = indicatorStr;
    }
}


