
package ui;

import javax.swing.JOptionPane;
import unit.manager.DuocPhamDataManager;
import worker.ErrorLoger;

/**
 *
 * @author Thanh Nhan <JackV at congdongjava.com>
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtUsename = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pPassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        butLogin = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng Nhập");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel3.setText("Tài khoản ");
        jPanel1.add(jLabel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "nhập JackV", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        txtUsename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtUsename.setPreferredSize(new java.awt.Dimension(150, 30));
        txtUsename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsenameActionPerformed(evt);
            }
        });
        txtUsename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsenameFocusGained(evt);
            }
        });
        jPanel5.add(txtUsename);

        jPanel1.add(jPanel5);

        jPanel4.add(jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key.png"))); // NOI18N
        jLabel4.setText(" Mật khẩu ");
        jPanel2.add(jLabel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "nhập congdongjava.com", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        pPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pPassword.setPreferredSize(new java.awt.Dimension(150, 30));
        pPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPasswordActionPerformed(evt);
            }
        });
        pPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pPasswordFocusGained(evt);
            }
        });
        jPanel6.add(pPassword);

        jPanel2.add(jPanel6);

        jPanel4.add(jPanel2);

        butLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/locked.png"))); // NOI18N
        butLogin.setText("Đăng Nhập");
        butLogin.setMargin(new java.awt.Insets(2, 7, 2, 14));
        butLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/locked.png"))); // NOI18N
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        jPanel7.add(butLogin);

        jPanel4.add(jPanel7);

        add(jPanel4, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    int iCount = 0;
    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        try {
            if (DuocPhamDataManager.isValidAccessInfo(txtUsename.getText(), String.valueOf(pPassword.getPassword()))) {
                MainFrame.it.loadPanelControl();
            } else {
                JOptionPane.showMessageDialog(this, "Tài khoản không đúng");
                iCount++;
                if (iCount == 3) {
                    
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi:" + ex.getMessage());
			ex.printStackTrace();ex.printStackTrace(ErrorLoger.getLogStream());
        }
    }//GEN-LAST:event_butLoginActionPerformed

    private void pPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPasswordActionPerformed
        butLogin.doClick();
    }//GEN-LAST:event_pPasswordActionPerformed

    private void txtUsenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsenameActionPerformed
        pPassword.requestFocus();
    }//GEN-LAST:event_txtUsenameActionPerformed

    private void txtUsenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsenameFocusGained
        txtUsename.selectAll();
    }//GEN-LAST:event_txtUsenameFocusGained

    private void pPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pPasswordFocusGained
        pPassword.selectAll();
    }//GEN-LAST:event_pPasswordFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField pPassword;
    private javax.swing.JTextField txtUsename;
    // End of variables declaration//GEN-END:variables
}
