package com.isofh.hibernate.entities;
// Generated May 24, 2016 4:58:58 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HisPatient generated by hbm2java
 */
public class HisPatient  implements java.io.Serializable {


     private long hisPatientId;
     private long adClientId;
     private long adOrgId;
     private String address1;
     private String address2;
     private Long age;
     private Long assurancecardId;
     private Date assuranceFromdate;
     private String assuranceId;
     private String assuranceRegisteredat;
     private Date assuranceTodate;
     private Date birthday;
     private Date created;
     private Long createdby;
     private String guardianidNo;
     private String guardianname;
     private String guardiantelno;
     private Long hisCountryId;
     private Long hisDistrictId;
     private Long hisJobId;
     private Long hisProvinceId;
     private Long hisServiceId;
     private String hisZone;
     private String idNo;
     private Character isactive;
     private String name;
     private String telNo;
     private Date updated;
     private Long updatedby;
     private String code;
     private Character hisGenderId;
     private String hisPatienttypeId;
     private Long patientfromHospitalId;
     private Long assuranceRegathospitalId;
     private Long hisZoneId;
     private String value;
     private Long inhospitalcount;
     private Long hisSyncId;
     private Long outpatientcounta;
     private Long outpatientcountabymonth;
     private Long outpatientcountabyyear;
     private Long outpatientcount;
     private Long hisDepartmentId;
     private String regionvalue;

    public HisPatient() {
    }

	
    public HisPatient(long hisPatientId, long adClientId, long adOrgId) {
        this.hisPatientId = hisPatientId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
    }
    public HisPatient(long hisPatientId, long adClientId, long adOrgId, String address1, String address2, Long age, Long assurancecardId, Date assuranceFromdate, String assuranceId, String assuranceRegisteredat, Date assuranceTodate, Date birthday, Date created, Long createdby, String guardianidNo, String guardianname, String guardiantelno, Long hisCountryId, Long hisDistrictId, Long hisJobId, Long hisProvinceId, Long hisServiceId, String hisZone, String idNo, Character isactive, String name, String telNo, Date updated, Long updatedby, String code, Character hisGenderId, String hisPatienttypeId, Long patientfromHospitalId, Long assuranceRegathospitalId, Long hisZoneId, String value, Long inhospitalcount, Long hisSyncId, Long outpatientcounta, Long outpatientcountabymonth, Long outpatientcountabyyear, Long outpatientcount, Long hisDepartmentId, String regionvalue) {
       this.hisPatientId = hisPatientId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.address1 = address1;
       this.address2 = address2;
       this.age = age;
       this.assurancecardId = assurancecardId;
       this.assuranceFromdate = assuranceFromdate;
       this.assuranceId = assuranceId;
       this.assuranceRegisteredat = assuranceRegisteredat;
       this.assuranceTodate = assuranceTodate;
       this.birthday = birthday;
       this.created = created;
       this.createdby = createdby;
       this.guardianidNo = guardianidNo;
       this.guardianname = guardianname;
       this.guardiantelno = guardiantelno;
       this.hisCountryId = hisCountryId;
       this.hisDistrictId = hisDistrictId;
       this.hisJobId = hisJobId;
       this.hisProvinceId = hisProvinceId;
       this.hisServiceId = hisServiceId;
       this.hisZone = hisZone;
       this.idNo = idNo;
       this.isactive = isactive;
       this.name = name;
       this.telNo = telNo;
       this.updated = updated;
       this.updatedby = updatedby;
       this.code = code;
       this.hisGenderId = hisGenderId;
       this.hisPatienttypeId = hisPatienttypeId;
       this.patientfromHospitalId = patientfromHospitalId;
       this.assuranceRegathospitalId = assuranceRegathospitalId;
       this.hisZoneId = hisZoneId;
       this.value = value;
       this.inhospitalcount = inhospitalcount;
       this.hisSyncId = hisSyncId;
       this.outpatientcounta = outpatientcounta;
       this.outpatientcountabymonth = outpatientcountabymonth;
       this.outpatientcountabyyear = outpatientcountabyyear;
       this.outpatientcount = outpatientcount;
       this.hisDepartmentId = hisDepartmentId;
       this.regionvalue = regionvalue;
    }
   
    public long getHisPatientId() {
        return this.hisPatientId;
    }
    
    public void setHisPatientId(long hisPatientId) {
        this.hisPatientId = hisPatientId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public Long getAge() {
        return this.age;
    }
    
    public void setAge(Long age) {
        this.age = age;
    }
    public Long getAssurancecardId() {
        return this.assurancecardId;
    }
    
    public void setAssurancecardId(Long assurancecardId) {
        this.assurancecardId = assurancecardId;
    }
    public Date getAssuranceFromdate() {
        return this.assuranceFromdate;
    }
    
    public void setAssuranceFromdate(Date assuranceFromdate) {
        this.assuranceFromdate = assuranceFromdate;
    }
    public String getAssuranceId() {
        return this.assuranceId;
    }
    
    public void setAssuranceId(String assuranceId) {
        this.assuranceId = assuranceId;
    }
    public String getAssuranceRegisteredat() {
        return this.assuranceRegisteredat;
    }
    
    public void setAssuranceRegisteredat(String assuranceRegisteredat) {
        this.assuranceRegisteredat = assuranceRegisteredat;
    }
    public Date getAssuranceTodate() {
        return this.assuranceTodate;
    }
    
    public void setAssuranceTodate(Date assuranceTodate) {
        this.assuranceTodate = assuranceTodate;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }
    public String getGuardianidNo() {
        return this.guardianidNo;
    }
    
    public void setGuardianidNo(String guardianidNo) {
        this.guardianidNo = guardianidNo;
    }
    public String getGuardianname() {
        return this.guardianname;
    }
    
    public void setGuardianname(String guardianname) {
        this.guardianname = guardianname;
    }
    public String getGuardiantelno() {
        return this.guardiantelno;
    }
    
    public void setGuardiantelno(String guardiantelno) {
        this.guardiantelno = guardiantelno;
    }
    public Long getHisCountryId() {
        return this.hisCountryId;
    }
    
    public void setHisCountryId(Long hisCountryId) {
        this.hisCountryId = hisCountryId;
    }
    public Long getHisDistrictId() {
        return this.hisDistrictId;
    }
    
    public void setHisDistrictId(Long hisDistrictId) {
        this.hisDistrictId = hisDistrictId;
    }
    public Long getHisJobId() {
        return this.hisJobId;
    }
    
    public void setHisJobId(Long hisJobId) {
        this.hisJobId = hisJobId;
    }
    public Long getHisProvinceId() {
        return this.hisProvinceId;
    }
    
    public void setHisProvinceId(Long hisProvinceId) {
        this.hisProvinceId = hisProvinceId;
    }
    public Long getHisServiceId() {
        return this.hisServiceId;
    }
    
    public void setHisServiceId(Long hisServiceId) {
        this.hisServiceId = hisServiceId;
    }
    public String getHisZone() {
        return this.hisZone;
    }
    
    public void setHisZone(String hisZone) {
        this.hisZone = hisZone;
    }
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTelNo() {
        return this.telNo;
    }
    
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(Long updatedby) {
        this.updatedby = updatedby;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Character getHisGenderId() {
        return this.hisGenderId;
    }
    
    public void setHisGenderId(Character hisGenderId) {
        this.hisGenderId = hisGenderId;
    }
    public String getHisPatienttypeId() {
        return this.hisPatienttypeId;
    }
    
    public void setHisPatienttypeId(String hisPatienttypeId) {
        this.hisPatienttypeId = hisPatienttypeId;
    }
    public Long getPatientfromHospitalId() {
        return this.patientfromHospitalId;
    }
    
    public void setPatientfromHospitalId(Long patientfromHospitalId) {
        this.patientfromHospitalId = patientfromHospitalId;
    }
    public Long getAssuranceRegathospitalId() {
        return this.assuranceRegathospitalId;
    }
    
    public void setAssuranceRegathospitalId(Long assuranceRegathospitalId) {
        this.assuranceRegathospitalId = assuranceRegathospitalId;
    }
    public Long getHisZoneId() {
        return this.hisZoneId;
    }
    
    public void setHisZoneId(Long hisZoneId) {
        this.hisZoneId = hisZoneId;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Long getInhospitalcount() {
        return this.inhospitalcount;
    }
    
    public void setInhospitalcount(Long inhospitalcount) {
        this.inhospitalcount = inhospitalcount;
    }
    public Long getHisSyncId() {
        return this.hisSyncId;
    }
    
    public void setHisSyncId(Long hisSyncId) {
        this.hisSyncId = hisSyncId;
    }
    public Long getOutpatientcounta() {
        return this.outpatientcounta;
    }
    
    public void setOutpatientcounta(Long outpatientcounta) {
        this.outpatientcounta = outpatientcounta;
    }
    public Long getOutpatientcountabymonth() {
        return this.outpatientcountabymonth;
    }
    
    public void setOutpatientcountabymonth(Long outpatientcountabymonth) {
        this.outpatientcountabymonth = outpatientcountabymonth;
    }
    public Long getOutpatientcountabyyear() {
        return this.outpatientcountabyyear;
    }
    
    public void setOutpatientcountabyyear(Long outpatientcountabyyear) {
        this.outpatientcountabyyear = outpatientcountabyyear;
    }
    public Long getOutpatientcount() {
        return this.outpatientcount;
    }
    
    public void setOutpatientcount(Long outpatientcount) {
        this.outpatientcount = outpatientcount;
    }
    public Long getHisDepartmentId() {
        return this.hisDepartmentId;
    }
    
    public void setHisDepartmentId(Long hisDepartmentId) {
        this.hisDepartmentId = hisDepartmentId;
    }
    public String getRegionvalue() {
        return this.regionvalue;
    }
    
    public void setRegionvalue(String regionvalue) {
        this.regionvalue = regionvalue;
    }




}


